#!/usr/bin/env python3
"""Regenerate Unicode helper tables used by cpp/src/lang-specific/spanish.cpp."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "cpp" / "src" / "lang-specific"


def esc_cpp_utf8(s: str) -> str:
    return '"' + "".join(f"\\x{b:02x}" for b in s.encode("utf-8")) + '"'


def write_strip() -> None:
    import unicodedata

    def strip_string(ch: str) -> str:
        return "".join(
            c for c in unicodedata.normalize("NFD", ch) if unicodedata.category(c) != "Mn"
        )

    pairs: list[tuple[int, str]] = []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        st = strip_string(ch)
        if st != ch:
            pairs.append((cp, st))
    pairs.sort(key=lambda x: x[0])

    path = OUT / "spanish_unicode_strip.inc"
    lines = [
        "// AUTO-GENERATED by scripts/gen_spanish_unicode_tables.py — do not edit.",
        "static const std::pair<char32_t, const char*> k_unicode_strip_table[] = {",
    ]
    for cp, st in pairs:
        lines.append(f"  {{U'\\U{cp:08x}', {esc_cpp_utf8(st)}}},")
    lines.append("};")
    lines.append(f"static const size_t k_unicode_strip_table_size = {len(pairs)};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", path, len(pairs), "entries")


def write_lower() -> None:
    pairs: list[tuple[int, str]] = []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        lo = ch.lower()
        if lo != ch:
            pairs.append((cp, lo))
    pairs.sort(key=lambda x: x[0])

    path = OUT / "spanish_unicode_lower.inc"
    lines = [
        "// AUTO-GENERATED by scripts/gen_spanish_unicode_tables.py — do not edit.",
        "static const std::pair<char32_t, const char*> k_unicode_lower_table[] = {",
    ]
    for cp, lo in pairs:
        lines.append(f"  {{U'\\U{cp:08x}', {esc_cpp_utf8(lo)}}},")
    lines.append("};")
    lines.append(f"static const size_t k_unicode_lower_table_size = {len(pairs)};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", path, len(pairs), "entries")


def write_word_bitmap() -> None:
    patw = re.compile(r"\w", re.UNICODE)
    max_cp = 0x110000
    nw = (max_cp + 31) // 32
    words = [0] * nw
    for cp in range(max_cp):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        if patw.match(chr(cp)):
            words[cp // 32] |= 1 << (cp % 32)

    path = OUT / "spanish_unicode_word_bitmap.inc"
    lines = [
        "// AUTO-GENERATED by scripts/gen_spanish_unicode_tables.py — do not edit.",
        "// Python 3 re \\w (UNICODE).",
        f"static constexpr uint32_t k_unicode_word_bitmap_words = {nw}u;",
        "static const uint32_t k_unicode_word_bitmap[] = {",
    ]
    for i in range(0, len(words), 8):
        chunk = words[i : i + 8]
        lines.append("  " + ", ".join(f"0x{w:08x}u" for w in chunk) + ",")
    lines.append("};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", path, nw, "words")


def write_space_bitmap() -> None:
    max_cp = 0x110000
    nw = (max_cp + 31) // 32
    words = [0] * nw
    for cp in range(max_cp):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        if chr(cp).isspace():
            words[cp // 32] |= 1 << (cp % 32)

    path = OUT / "spanish_unicode_space_bitmap.inc"
    lines = [
        "// AUTO-GENERATED by scripts/gen_spanish_unicode_tables.py — do not edit.",
        "// Python 3 str.isspace().",
        f"static constexpr uint32_t k_unicode_space_bitmap_words = {nw}u;",
        "static const uint32_t k_unicode_space_bitmap[] = {",
    ]
    for i in range(0, len(words), 8):
        chunk = words[i : i + 8]
        lines.append("  " + ", ".join(f"0x{w:08x}u" for w in chunk) + ",")
    lines.append("};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", path, nw, "words")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    write_strip()
    write_lower()
    write_word_bitmap()
    write_space_bitmap()


if __name__ == "__main__":
    main()
