#!/usr/bin/env python3
"""Regenerate Unicode helper tables in cpp/src/lang-specific/spanish_unicode_tables.cpp."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "cpp" / "src" / "lang-specific"
CPP_PATH = OUT_DIR / "spanish_unicode_tables.cpp"


def esc_cpp_utf8(s: str) -> str:
    return '"' + "".join(f"\\x{b:02x}" for b in s.encode("utf-8")) + '"'


def gen_strip() -> list[str]:
    import unicodedata

    def strip_string(ch: str) -> str:
        return "".join(
            c for c in unicodedata.normalize("NFD", ch) if unicodedata.category(c) != "Mn"
        )

    pairs: list[tuple[int, str]] = []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        st = strip_string(ch)
        if st != ch:
            pairs.append((cp, st))
    pairs.sort(key=lambda x: x[0])

    lines = [
        "// AUTO-GENERATED by scripts/gen_spanish_unicode_tables.py — do not edit.",
        "const std::pair<char32_t, const char*> k_unicode_strip_table[] = {",
    ]
    for cp, st in pairs:
        lines.append(f"  {{U'\\U{cp:08x}', {esc_cpp_utf8(st)}}},")
    lines.append("};")
    lines.append(f"const size_t k_unicode_strip_table_size = {len(pairs)};")
    return lines


def gen_lower() -> list[str]:
    pairs: list[tuple[int, str]] = []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        lo = ch.lower()
        if lo != ch:
            pairs.append((cp, lo))
    pairs.sort(key=lambda x: x[0])

    lines = [
        "// AUTO-GENERATED by scripts/gen_spanish_unicode_tables.py — do not edit.",
        "const std::pair<char32_t, const char*> k_unicode_lower_table[] = {",
    ]
    for cp, lo in pairs:
        lines.append(f"  {{U'\\U{cp:08x}', {esc_cpp_utf8(lo)}}},")
    lines.append("};")
    lines.append(f"const size_t k_unicode_lower_table_size = {len(pairs)};")
    return lines


def gen_word_bitmap() -> list[str]:
    patw = re.compile(r"\w", re.UNICODE)
    max_cp = 0x110000
    nw = (max_cp + 31) // 32
    words = [0] * nw
    for cp in range(max_cp):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        if patw.match(chr(cp)):
            words[cp // 32] |= 1 << (cp % 32)

    lines = [
        "// AUTO-GENERATED by scripts/gen_spanish_unicode_tables.py — do not edit.",
        "// Python 3 re \\w (UNICODE).",
        f"constexpr uint32_t k_unicode_word_bitmap_words = {nw}u;",
        "const uint32_t k_unicode_word_bitmap[] = {",
    ]
    for i in range(0, len(words), 8):
        chunk = words[i : i + 8]
        lines.append("  " + ", ".join(f"0x{w:08x}u" for w in chunk) + ",")
    lines.append("};")
    return lines


def gen_space_bitmap() -> list[str]:
    max_cp = 0x110000
    nw = (max_cp + 31) // 32
    words = [0] * nw
    for cp in range(max_cp):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        if chr(cp).isspace():
            words[cp // 32] |= 1 << (cp % 32)

    lines = [
        "// AUTO-GENERATED by scripts/gen_spanish_unicode_tables.py — do not edit.",
        "// Python 3 str.isspace().",
        f"constexpr uint32_t k_unicode_space_bitmap_words = {nw}u;",
        "const uint32_t k_unicode_space_bitmap[] = {",
    ]
    for i in range(0, len(words), 8):
        chunk = words[i : i + 8]
        lines.append("  " + ", ".join(f"0x{w:08x}u" for w in chunk) + ",")
    lines.append("};")
    return lines


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    strip_lines = gen_strip()
    lower_lines = gen_lower()
    word_lines = gen_word_bitmap()
    space_lines = gen_space_bitmap()

    parts = [
        '#include "moonshine_g2p/lang-specific/spanish_unicode_tables.hpp"',
        "",
        "namespace moonshine_g2p::spanish_unicode {",
        "",
        "\n".join(strip_lines),
        "",
        "\n".join(lower_lines),
        "",
        "\n".join(word_lines),
        "",
        "\n".join(space_lines),
        "",
        "}  // namespace moonshine_g2p::spanish_unicode",
        "",
    ]
    CPP_PATH.write_text("\n".join(parts), encoding="utf-8")
    print("wrote", CPP_PATH)


if __name__ == "__main__":
    main()
