#!/usr/bin/env python3
"""Regenerate ``cpp/src/japanese-mora-data.inc`` from :mod:`japanese_kana_to_ipa` (single source of truth)."""

from __future__ import annotations

import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO))

import japanese_kana_to_ipa as j  # noqa: E402


def main() -> None:
    out_path = _REPO / "cpp" / "src" / "japanese-mora-data.inc"
    m = j._MORA
    items = sorted(m.items(), key=lambda kv: len(kv[0].encode("utf-8")), reverse=True)
    lines = [
        "// Generated by scripts/gen_japanese_mora_inc.py — do not edit by hand.",
        "static const std::vector<std::pair<std::string, std::pair<std::string, std::string>>> "
        "kMoraDesc = {",
    ]
    for k, (o, n) in items:

        def esc(s: str) -> str:
            return s.replace("\\", "\\\\").replace('"', '\\"')

        # Plain UTF-8 string literals (file UTF-8); avoid u8"" which is char8_t in C++20.
        lines.append(f'  {{"{esc(k)}", {{"{esc(o)}", "{esc(n)}"}}}},')
    lines.append("};")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote", out_path)


if __name__ == "__main__":
    main()
